- admin/admin_main.php
- admin/show_tickets.php
> Widen admin_main and show_tickets to the full page

- admin/admin_reply_ticket.php
- admin/admin_settings.php
- admin/admin_settings_save.php
- admin/admin_ticket.php
- inc/email_functions.inc.php
- install/mods-for-hesk/sql/installSql.php
- language/en/text.php
- modsForHesk_settings.inc.php
- reply_ticket.php
> Attachments in emails

- css/hesk_newStyle.php
- css/hesk_newStyleRTL.php
- inc/knowledgebase_functions.inc.php
- knowledgebase.php
- language/en/text.php
> Fix knowledgebase

- admin/admin_ticket.php
- admin/mail.php
- inc/email_functions.inc.php
> Fix attachments

- admin/admin_settings.php
- admin/knowledgebase_private.php
- admin/mail.php
- admin/manage_knowledgebase.php
- admin/new_ticket.php
- admin/reports.php
- inc/knowledgebase_functions.inc.php
- index.php
> Alignment issues

- css/hesk_newStyle.php
- css/hesk_newStyleRTL.php
- inc/knowledgebase_functions.inc.php
- index.php
- language/en/text.php
- Use Bootstrap panels instead of custom CSS
- Show top/latest KB articles based on values in settings
Closes #205
> Dashboard Tweaks

- inc/email_functions.inc.php
- submit_ticket.php
> Fix attachments for creating new tickets

- admin/admin_reply_ticket.php
- admin/admin_ticket.php
- admin/change_status.php
- admin/edit_post.php
- admin/manage_categories.php
- admin/manage_users.php
- install/mods-for-hesk/sql/installSql.php
- language/en/text.php
> Designate category manager

- inc/show_admin_nav.inc.php
> Don't show the KB link if KB is disabled

- admin/admin_ticket.php
> Fix response layouts

- admin/manage_knowledgebase.php
> Hopefully fixed the footer...again

- admin/new_ticket.php
- index.php
- js/modsForHesk-javascript.js
> Display map div only after getting location

- admin/admin_settings.php
- admin/admin_settings_save.php
- admin/admin_ticket.php
- admin/export.php
- admin/manage_categories.php
- admin/manage_permission_templates.php
- admin/manage_users.php
- admin/new_ticket.php
- inc/ticket_list.inc.php
- index.php
- language/en/text.php
- modsForHesk_settings.inc.php
> Sort categories alphabetically

- admin/admin_settings.php
- admin/admin_settings_save.php
- index.php
- install/mods-for-hesk/sql/installSql.php
- knowledgebase.php
- language/en/text.php
- ticket.php
> Hide quick help sections

- admin/manage_canned.php
> Always show custom field selection when editing canned response

- .gitignore
- inc/recaptcha/recaptchalib_v2.php
> Add cURL Support for reCAPTCHA v2

- admin/admin_main.php
- admin/admin_settings.php
- admin/admin_settings_save.php
- admin/admin_ticket.php
- admin/change_status.php
- admin/export.php
- admin/manage_statuses.php
- admin/show_tickets.php
- inc/common.inc.php
- inc/print_tickets.inc.php
- inc/show_search_form.inc.php
- inc/status_functions.inc.php
- inc/ticket_list.inc.php
- install/mods-for-hesk/ajax/task-ajax.php
- install/mods-for-hesk/installModsForHesk.php
- install/mods-for-hesk/js/version-scripts.js
- install/mods-for-hesk/sql/installSql.php
- language/en/text.php
- modsForHesk_settings.inc.php
- ticket.php
Closes #209. Will need to make sure installation migration works properly before release.
> Improve Statuses UI

- admin/admin_reply_ticket.php
- admin/admin_settings.php
- admin/admin_settings_save.php
- admin/admin_submit_ticket.php
- admin/admin_ticket.php
- admin/edit_post.php
- admin/manage_canned.php
- admin/manage_ticket_templates.php
- admin/new_ticket.php
- css/hesk_newStyle.php
- css/hesk_newStyleRTL.php
- inc/header.inc.php
- inc/htmLawed.php
- inc/pipe_functions.inc.php
- inc/posting_functions.inc.php
- index.php
- install/mods-for-hesk/sql/installSql.php
- language/en/text.php
- modsForHesk_settings.inc.php
- print.php
- submit_ticket.php
- ticket.php
> Tiny mce for tickets

- inc/email_functions.inc.php
> Don't send email if all email fields are empty

- install/mods-for-hesk/sql/installSql.php
> Add statuses key to tickets table in the very beginning upgrade

- admin/admin_submit_ticket.php
- inc/pipe_functions.inc.php
> Fix some 0kb attachment issues

- admin/manage_statuses.php
- language/en/text.php
> Fix some status stuff before release

- .gitignore
- admin/admin_settings.php
- admin/admin_settings_save.php
- admin/admin_ticket.php
- admin/manage_knowledgebase.php
- download_attachment.php
- inc/attachments.inc.php
- inc/common.inc.php
- inc/view_attachment_functions.inc.php
- install/mods-for-hesk/sql/installSql.php
- language/en/text.php
- modsForHesk_settings.inc.php
- ticket.php
> Attachment improvements, phase one

- admin/admin_ticket.php
- admin/manage_canned.php
- admin/manage_statuses.php
- admin/new_ticket.php
- inc/common.inc.php
- install/install_functions.inc.php
- install/mods-for-hesk/ajax/install-database-ajax.php
- install/mods-for-hesk/installModsForHesk.php
- install/mods-for-hesk/js/version-scripts.js
- install/mods-for-hesk/modsForHesk.php
- install/mods-for-hesk/sql/installSql.php
- install/mods-for-hesk/sql/uninstallSql.php
> Update installer, fix status issues, fix TinyMCE issues

- admin/admin_settings.php
> Remove deprecated panel

- inc/admin_functions.inc.php
> Fix rare merge issue

- admin/manage_statuses.php
- language/en/text.php
> Add tooltips to statuses page and fix create status issue

- admin/admin_settings.php
> Improve check for update ux

- admin/admin_reply_ticket.php
- admin/admin_submit_ticket.php
- admin/admin_ticket.php
- inc/posting_functions.inc.php
- install/mods-for-hesk/sql/installSql.php
- print.php
- reply_ticket.php
- submit_ticket.php
- ticket.php
> Only render HTML if the ticket was created with it enabled

- admin/admin_settings.php
- admin/admin_settings_save.php
- inc/view_attachment_functions.inc.php
- index.php
- install/install_functions.inc.php
- install/mods-for-hesk/ajax/install-database-ajax.php
- install/mods-for-hesk/js/version-scripts.js
- install/mods-for-hesk/modsForHesk.php
- install/mods-for-hesk/sql/installSql.php
- modsForHesk_settings.inc.php
- reply_ticket.php
- submit_ticket.php
- ticket.php
> 2.4.1 Changes

- admin/edit_post.php
- reply_ticket.php
- submit_ticket.php
> Fix extra line breaks in HTML templates

- admin/manage_email_templates.php
- inc/email_functions.inc.php
- language/en/text.php
> Add MESSAGE_NO_ATTACHMENTS tag

- css/hesk_newStyleRTL.css
- inc/header.inc.php
- inc/headerAdmin.inc.php
> Rename the RTL css file from .php to .css

- install/mods-for-hesk/installModsForHesk.php
- install/mods-for-hesk/modsForHesk.php
> Remove v prefix from version numbers

- install/mods-for-hesk/installModsForHesk.php
- install/mods-for-hesk/js/version-scripts.js
- install/mods-for-hesk/modsForHesk.php
> Use build numbers instead of version numbers

- install/mods-for-hesk/js/version-scripts.js
> fix css classes

- admin/admin_settings.php
- admin/admin_settings_save.php
- admin/edit_post.php
- admin/new_ticket.php
- admin/options.php
- index.php
- language/en/text.php
> New custom fields

- admin/admin_main.php
- admin/admin_settings.php
- admin/banned_emails.php
- admin/banned_ips.php
- admin/export.php
- admin/find_tickets.php
- admin/mail.php
- admin/manage_canned.php
- admin/manage_categories.php
- admin/manage_email_templates.php
- admin/manage_knowledgebase.php
- admin/manage_permission_templates.php
- admin/manage_statuses.php
- admin/manage_ticket_templates.php
- admin/manage_users.php
- admin/new_ticket.php
- admin/profile.php
- admin/reports.php
- admin/service_messages.php
- admin/show_tickets.php
- css/hesk_newStyle.css
- css/hesk_newStyleRTL.css
- css/mods-for-hesk.css
- inc/header.inc.php
- inc/headerAdmin.inc.php
- index.php
- knowledgebase.php
- ticket.php
> Remove some inline styling

- admin/admin_settings.php
- admin/admin_settings_save.php
- inc/header.inc.php
- inc/show_admin_nav.inc.php
- install/mods-for-hesk/sql/installSql.php
- language/en/text.php
> Add setting for navbar title url

- admin/admin_main.php
- admin/admin_settings.php
- admin/banned_emails.php
- admin/banned_ips.php
- admin/export.php
- admin/find_tickets.php
- admin/knowledgebase_private.php
- admin/mail.php
- admin/manage_canned.php
- admin/manage_categories.php
- admin/manage_email_templates.php
- admin/manage_knowledgebase.php
- admin/manage_permission_templates.php
- admin/manage_statuses.php
- admin/manage_ticket_templates.php
- admin/manage_users.php
- admin/profile.php
- admin/reports.php
- admin/service_messages.php
- admin/show_tickets.php
- inc/header.inc.php
- inc/headerAdmin.inc.php
- inc/show_admin_nav.inc.php
- index.php
- knowledgebase.php
- ticket.php
> Indicate active page on navbar

- index.php
> Fix custom field requirements

- admin/password.php
Fixes #423 remove extra call to load DB functions
> Fix Password Reset Page

- admin/edit_post.php
> Update HTML property when editing ticket/reply

- admin/new_ticket.php
> Fix custom field query string parsing on admin side

- admin/change_status.php
> Update ticket status before sending email

- admin/admin_settings_save.php
> Save mailgun settings

- admin/manage_users.php
- admin/profile.php
> Fix signature limit

- admin/admin_ticket.php
Unable to open a ticket in admin area with error:
PHP Parse error:  syntax error, unexpected '[', expecting ')'
> Unexpected [ bug fix
